// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBs2IsJokhKzsH51XkXD6CUMQOsp1LNJB8',
    appId: '1:522942087181:web:0b181a0a0f456b08d4d544',
    messagingSenderId: '522942087181',
    projectId: 'agri-ledger-c427d',
    authDomain: 'agri-ledger-c427d.firebaseapp.com',
    storageBucket: 'agri-ledger-c427d.firebasestorage.app',
    measurementId: 'G-DFNS0P5WMH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0wr-26_FkOrLUcxjeYoAKHH43-htGoyw',
    appId: '1:522942087181:android:dbefc4e562f60769d4d544',
    messagingSenderId: '522942087181',
    projectId: 'agri-ledger-c427d',
    storageBucket: 'agri-ledger-c427d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwYDiji3K_5KenBmiy_gF8NCrSVmTSk_0',
    appId: '1:522942087181:ios:241b366c7d0ccbcad4d544',
    messagingSenderId: '522942087181',
    projectId: 'agri-ledger-c427d',
    storageBucket: 'agri-ledger-c427d.firebasestorage.app',
    iosBundleId: 'com.example.agriLedger',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwYDiji3K_5KenBmiy_gF8NCrSVmTSk_0',
    appId: '1:522942087181:ios:241b366c7d0ccbcad4d544',
    messagingSenderId: '522942087181',
    projectId: 'agri-ledger-c427d',
    storageBucket: 'agri-ledger-c427d.firebasestorage.app',
    iosBundleId: 'com.example.agriLedger',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBs2IsJokhKzsH51XkXD6CUMQOsp1LNJB8',
    appId: '1:522942087181:web:9de97cd0ad9aba20d4d544',
    messagingSenderId: '522942087181',
    projectId: 'agri-ledger-c427d',
    authDomain: 'agri-ledger-c427d.firebaseapp.com',
    storageBucket: 'agri-ledger-c427d.firebasestorage.app',
    measurementId: 'G-BQLWN81N3X',
  );
}
